### ISSUE TITLE
 An error occurred during training grefcoco datasets

### ISSUE THREAD

**Issue by zhanght021** [Dmmm1997/SimVG#3]
During the training process of the RefCOCO dataset, the following error will occur.

  File "/home/XXXXX/SimVG-main/simvg/apis/train.py", line 49, in train_model
    for batch, inputs in enumerate(loader):
  File "/usr/local/python3.10.12/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/usr/local/python3.10.12/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 673, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/usr/local/python3.10.12/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/python3.10.12/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 52, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/XXXXX/SimVG-main/simvg/datasets/base.py", line 70, in __getitem__
    results = self.pipeline(results)
  File "/home/XXXXX/SimVG-main/simvg/datasets/pipelines/compose.py", line 22, in __call__
    results = transform(results)
  File "/home/XXXXX/SimVG-main/simvg/datasets/pipelines/loading.py", line 275, in __call__
    results = self._load_expression_tokenize_beit3(results)
  File "/home/XXXXX/SimVG-main/simvg/datasets/pipelines/loading.py", line 162, in _load_expression_tokenize_beit3
    expression = expressions[self.random_ind]
KeyError: 0

**Comment by moqj** [comment]
I've run into a similar issue. Is there any solution for it? @zhanght021 @Dmmm1997 

```
Traceback (most recent call last):
  File "tools/train.py", line 223, in <module>
    main()
  File "tools/train.py", line 219, in main
    main_worker(cfg)
  File "tools/train.py", line 121, in main_worker
    train_model(epoch, cfg, model, model_ema, optimizer, dataloaders[0])
  File "/home/gpu18/workspace/SimVG/simvg/apis/train.py", line 49, in train_model
    for batch, inputs in enumerate(loader):
  File "/home/gpu18/anaconda3/envs/vg/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/home/gpu18/anaconda3/envs/vg/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1344, in _next_data
    return self._process_data(data)
  File "/home/gpu18/anaconda3/envs/vg/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1370, in _process_data
    data.reraise()
  File "/home/gpu18/anaconda3/envs/vg/lib/python3.8/site-packages/torch/_utils.py", line 706, in reraise
    raise exception
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/gpu18/anaconda3/envs/vg/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 309, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
  File "/home/gpu18/anaconda3/envs/vg/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/gpu18/anaconda3/envs/vg/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 52, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/gpu18/workspace/SimVG/simvg/datasets/base.py", line 70, in __getitem__
    results = self.pipeline(results)
  File "/home/gpu18/workspace/SimVG/simvg/datasets/pipelines/compose.py", line 22, in __call__
    results = transform(results)
  File "/home/gpu18/workspace/SimVG/simvg/datasets/pipelines/loading.py", line 272, in __call__
    results = self._load_expression_tokenize_beit3(results)
  File "/home/gpu18/workspace/SimVG/simvg/datasets/pipelines/loading.py", line 162, in _load_expression_tokenize_beit3
    expression = expressions[self.random_ind]
KeyError: 1
```

**Comment by Dmmm1997** [comment]
> During the training process of the RefCOCO dataset, the following error will occur.
> 
> File "/home/XXXXX/SimVG-main/simvg/apis/train.py", line 49, in train_model for batch, inputs in enumerate(loader): File "/usr/local/python3.10.12/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 630, in **next** data = self._next_data() File "/usr/local/python3.10.12/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 673, in _next_data data = self._dataset_fetcher.fetch(index) # may raise StopIteration File "/usr/local/python3.10.12/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch data = [self.dataset[idx] for idx in possibly_batched_index] File "/usr/local/python3.10.12/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 52, in data = [self.dataset[idx] for idx in possibly_batched_index] File "/home/XXXXX/SimVG-main/simvg/datasets/base.py", line 70, in **getitem** results = self.pipeline(results) File "/home/XXXXX/SimVG-main/simvg/datasets/pipelines/compose.py", line 22, in **call** results = transform(results) File "/home/XXXXX/SimVG-main/simvg/datasets/pipelines/loading.py", line 275, in **call** results = self._load_expression_tokenize_beit3(results) File "/home/XXXXX/SimVG-main/simvg/datasets/pipelines/loading.py", line 162, in _load_expression_tokenize_beit3 expression = expressions[self.random_ind] KeyError: 0

I have update the grefcoco dataset link.

https://seunic-my.sharepoint.cn/:f:/g/personal/230238525_seu_edu_cn/EiX51qGWa9BBlt3fVRwgPhsBUxOIZ-yW3Hm7VXOQ3c2Ipw?e=M12MM6

plz re-download the grefcoco dataset and pull the newest version of the code.
